### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by JayakumarManian** [jovotech/jovo-starter-web-chatwidget-react#1]
/Volumes/My MAC/Play-Groud/bot-workspace/jovo-starter-web-chatwidget-react/client/src/components/ChatWidget.tsx
TypeScript error in /Volumes/My MAC/Play-Groud/bot-workspace/jovo-starter-web-chatwidget-react/client/src/components/ChatWidget.tsx(25,23):
Property 'input' does not exist on type 'ClientRequest'.  TS2339

    23 |       {
    24 |         type: 'request',
  > 25 |         data: request.input || {},
       |                       ^
    26 |       },
    27 |     ]);
    28 |   };
^[[1;2B

**Comment by m-ripper** [comment]
Hello @JayakumarManian,

thanks for opening the issue. How did you try to build the client?

I've just tested it in the following way and it worked:
1. Clone repository
2. `npm i` in `client`
3. `npm run build` or `npm run start` to build/start the client

Another thing you could try is to delete `node_modules` and `package-lock.json` in `client` and try step 2.  and 3. again.

If this doesn't help you, just let me know.

**Comment by aswetlow** [comment]
Deleting `node_modules` and `packge-lock.json` worked for me.
